server:
  port: 8083
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/personas
    username: root
    password: root
    pool:
      enabled: true
      validation-query: "SELECT 1"
      max-idle-time: 30m

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics, prometheus, loggers, beans, env
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  info:
    git:
      mode: full
    build:
      enabled: true

logging:
  level:
    org.springframework.r2dbc.connection: DEBUG
    org.springframework.transaction: DEBUG
    io.r2dbc.pool: DEBUG


bootcamp-endpoint:
  base-url: "http://localhost:8082/bootcamp"
  timeout: "500"

report-endpoint:
  base-url: "http://localhost:8085/report"
  timeout: "500"